### ISSUE TITLE
serde 1.0 support?

### ISSUE THREAD

**Issue by mattmast** [mhallin/juniper#50]
I'm currently working on a project with serde v1.0.7 but I'm getting compilation errors when trying to serialize an execution result.

```
the trait `serde::Serialize` is not implemented for `juniper::Value`
the trait `serde::Serialize` is not implemented for `juniper::ExecutionError`
```

Is this expected?  Possibly user error?

**Comment by theduke** [comment]
It's because juniper still has serde version 0.9, which leads to the traits not being implemented for serde `1.0`.
